version: '3.7'

services:
  reverse:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - app1
      - app2
    restart: "on-failure"
  app1:
      image: my-node-app
      container_name: my-node-app
      environment:
          - TOKEN_SECRET=${TOKEN_SECRET}
          - PORT=${PORT}
          - DB_SERVER=${DB_SERVER}
          - REDIS_SERVER=${REDIS_SERVER}
          - DB_PORT=${DB_PORT}
          - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      ports:
        - 3000:3000
      depends_on:
        - db
        - redis
      volumes:
        - ./logs1:/usr/src/app/logs
      restart: "on-failure"
  app2:
      image: my-node-app
      container_name: my-node-app2
      environment:
          - TOKEN_SECRET=${TOKEN_SECRET}
          - PORT=${PORT}
          - DB_SERVER=${DB_SERVER}
          - REDIS_SERVER=${REDIS_SERVER}
          - DB_PORT=${DB_PORT}
          - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      ports:
        - 3002:3000
      depends_on:
        - db
        - redis
      volumes:
        - ./logs2:/usr/src/app/logs
      restart: "on-failure"
  redis:
    image: "redis:alpine"
    container_name: redis
    hostname: redis
    ports:
        - 6379:6379
    volumes:
      - ~/redis-data:/data
    restart: "on-failure"

  db:
    image: 'mongo'
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ~/mongodb-data:/data/db
